### ISSUE TITLE
[BUG] 侧边栏信息导致滚动卡顿

### ISSUE THREAD

**Issue by HTT-Solaca** [ChinaIceF/PyQt-SiliconUI#112]
当侧边栏信息增加的时候 切换到可滚动的页面会明显感觉到卡顿。且侧边栏信息越多越卡顿。

附[建议]：可以考虑部分侧边栏信息自动消失

**Comment by ChinaIceF** [comment]
你好，卡顿是阴影效果导致的，未来可能会考虑禁用阴影

此外，自动消息是支持的，例如启动 Gallery 弹出的欢迎消息会在 5sec 后自动消失，未来会在示例中添加一个输入框供输入自动消失时间

**Comment by ChinaIceF** [comment]
侧边栏信息过多时导致滚动卡顿的问题已经在这个pr里修复了
