### ISSUE TITLE
SiCombobox Issue

### ISSUE THREAD

**Issue by Starkikin** [ChinaIceF/PyQt-SiliconUI#122]
SiCombobox.addoption('text') ，无法在addwidget后更新添加， 文字显示不正确

**Comment by ChinaIceF** [comment]
### 需要更多信息

你好，我正在排查这个问题，请问是否方便提供一下你的相关代码

**Comment by Starkikin** [comment]
from PyQt5.QtCore import Qt
from siui.components.combobox import SiComboBox
from siui.components.page import SiPage
from siui.components import SiTitledWidgetGroup
from siui.core.silicon import Si
from siui.components.widgets import (
    SiDenseHContainer,
    SiDenseVContainer,
    SiLongPressButton,
    SiPushButton,
    SiSimpleButton,
    SiSwitch,
    SiToggleButton,
    SiLineEdit
)


class DebugWidgets(SiPage):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.setPadding(64)
        self.setScrollMaximumWidth(1000)
        self.setScrollAlignment(Qt.AlignLeft)
        self.setTitle("Combobox Check")

        self.titled_widgets_group = SiTitledWidgetGroup(self)
        self.titled_widgets_group.setSiliconWidgetFlag(Si.EnableAnimationSignals)

        with self.titled_widgets_group as group:
            group.addTitle("主窗口")

            container = SiDenseHContainer(self)
            label = SiPushButton(self)
            label.setUseTransition(True)
            label.resize(60, 32)
            label.attachment().setText('添加元素')
            label.clicked.connect(lambda: self.update_combobox_options())


            self.combobox = SiComboBox(self)
            self.combobox.resize(200, 32)
            self.combobox.addOption("空", (None,))
            self.combobox.menu().setShowIcon(False)

            container.addWidget(label)
            container.addWidget(self.combobox)

            group.addWidget(container)

            self.titled_widgets_group.addPlaceholder(64)
            self.setAttachment(self.titled_widgets_group)

    def update_combobox_options(self):
        #self.combobox.clearOptions()

        self.combobox.addOption("示例1", 1)
        self.combobox.addOption("示例2", 2)
        self.combobox.addOption("示例3", 3)
        self.combobox.addOption("示例4", 4)
        self.combobox.addOption("示例5", 5)
        self.combobox.addOption("示例6", 6)

当然我自己有加clearOptions， 不调用也行， 比如点击Button之后， addOption 确实有成功添加text, value， 但combobox的Menu内无法显示text

**Comment by ChinaIceF** [comment]
### 问题分析

这个问题应该源自于pyqt的逻辑，具体来说，所有在窗口创建后创建的控件，如果未运行`show()`，将不会显示

### 解决办法

你可以暂时使用以下代码，在创建完所有新添加的选项后运行，以对所有的选项运行`show()`:

```
for widget in self.combobox.menu().options():
    widget.show()
```

这应该可以解决这个问题，如果问题仍存在请继续反馈

**Comment by Starkikin** [comment]
![issue_window](https://github.com/user-attachments/assets/04aa72b2-10a3-4e06-94f1-0dfd4b9bbc8f)
从效果示意图来看，似乎不是widget.show()导致的，而且widget.show()似乎仍然没有解决该显示问题， 原因是它已经添加成功了并得到了update, 已新增了相应的menu框。 这个问题的原因好像text显示是被设计的背景或其不知道原因的方式导致的不更新兼容等问题而将其text遮挡了；   原生的Qcombobox可能没有融合更多的widget元素进去，更新的文字比较直观 。 不过没关系，它并不致命， 只是对于页面需要动态更新的场景变的不友好。
