### ISSUE TITLE
以example中的gallery为例，我该如何使用pyinstaller进行打包成exe

### ISSUE THREAD

**Issue by 605037300** [ChinaIceF/PyQt-SiliconUI#163]
以example中的gallery为例，我该如何使用pyinstaller进行打包成exe,或者用其他工具

**Comment by HTT-Solaca** [comment]
现在整个程序并不处于能够打包的状态 请等待原作者进行后续优化(因为程序中会直接运行siui目录下的文件 而siui并不在gallery目录下)

**Comment by ChinaIceF** [comment]
> 现在整个程序并不处于能够打包的状态 请等待原作者进行后续优化(因为程序中会直接运行siui目录下的文件 而siui并不在gallery目录下)

可以打包，只是我们现在在重新设计结构，会有很多的BREAKING，现在编写pyinstaller的模板过不会就用不了了，所以还没有提供相关教程。

**Comment by 605037300** [comment]
算是解决了，我直接把你siui的源码整个文件夹放过去，这样能直接找到
