### ISSUE TITLE
pyside6支持吗？

### ISSUE THREAD

**Issue by my-run** [ChinaIceF/PyQt-SiliconUI#188]
pyside6支持吗？

**Comment by rainzee** [comment]
暂时不支持，之后会支持

**Comment by H1DDENADM1N** [comment]
https://github.com/ChinaIceF/PyQt-SiliconUI/discussions/25

### 我将 [PySide6-SiliconUI](https://github.com/H1DDENADM1N/PySide6-SiliconUI) 分支同步更新到了 `v1.0.1`

**Comment by rainzee** [comment]
做为一个维护过多个 Qt 组件库，给上游 Qt 提交过 bug 写过代码的，其实 Widgets 平台存在的意义大部分情况下已经从传统 Desktop GUI 领域到了，工控机，医疗，航天等领域，该领域还存在大量的旧设备，需要 Qt5 的支持，目前最好的 Qt5 绑定就是 PyQt5，且由于你可能没有实际的工程经验，其实 PySide6 存在诸多问题，比较严重的是多媒体模块的内存泄漏和释放问题。组件库目前处在重构和设计阶段，将在很长一段时间内以 Qt5 为主导，PySide6 的绑定支持非常简单，只是我们要分清楚优先级，以上。
