### ISSUE TITLE
图中音乐播放器的图片为本地图片，如何更改为网络图片

### ISSUE THREAD

**Issue by xuanxuan-0403** [ChinaIceF/PyQt-SiliconUI#192]
![image](https://github.com/user-attachments/assets/7f4283b0-ba64-4bde-82f7-9352dd689ee2)
![2f3d310f48b9212b0920a7e3348d3f49](https://github.com/user-attachments/assets/fb7bf2c6-7c2f-4cb0-8bfd-40ed028b6b01)

**Comment by ChinaIceF** [comment]
这个就是一个示例，是开发的时候用来验证可行性的，以后可能会重制
