### ISSUE TITLE
下拉菜单报错

### ISSUE THREAD

**Issue by HowardJoness** [ChinaIceF/PyQt-SiliconUI#3]
如题 点击下拉菜单后出现如下报错
![image](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/143377834/0a89cb2b-c04e-45ae-92a6-d6e0dfda70df)
![屏幕截图 2024-06-22 163650](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/143377834/0d97afff-5929-4eb1-9764-5845f0f9b85f)

Traceback (most recent call last):
  File "C:\Users\Howard Jones\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyqt_siliconui-1.1-py3.12.egg\SiliconUI\SiMenu.py", line 215, in _popupAnimationHandler
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'int'
  resize(self, w: int, h: int): argument 2 has unexpected type 'float'

**Comment by HowardJoness** [comment]
![image](https://github.com/ChinaIceF/PyQt-SiliconUI/assets/143377834/6186dfc6-0870-4f46-be55-6406f1f5e788)
此处的下拉菜单也是

**Comment by ChinaIceF** [comment]
这个问题是由不同版本的python上的pyqt处理传入参数的方法不同导致的
** 我尝试修复了这个问题，请尝试重新下载仓库测试
如果问题仍然存在，请在下面留言

**Comment by HowardJoness** [comment]
已解决 谢谢
