### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by NB-Group** [ChinaIceF/PyQt-SiliconUI#76]
Ui组件都灰常好看！但是也有一些美中不足的地方。

1. 标题栏
![image](https://github.com/user-attachments/assets/cc0ff4ec-c901-4e2b-b1db-e7fe602c1f0f)
这个奇怪的标题栏既不能自适应系统主题，也不能同步程序界面内的颜色，只能说是拉的一批（

可以尝试用 css 把原生的去掉，再手动绘制一个捏。不介意的话，我可以帮你们改改

2. 卡
不知道是不是我的错觉，就感觉整个ui在滚动的时候都是卡卡的。

3. 滚动灵敏度太高辣
对于我这种使用笔记本电脑原生的触控板手势进行滚动的人不太友好，滚得太快辣

**Comment by learner20230724** [comment]
不知道是不是我的错觉，就感觉整个ui在滚动的时候都是卡卡的。
对的，8/17我用的时候也是这个感觉，真的卡。

**Comment by ChinaIceF** [comment]
**这应该是一个性能问题**，在换平台测试的时候我也注意到卡顿这个问题了

## 计划
计划使用 scroll 方法而非 move 方法处理滚动，这应该能减少不必要的重绘以增强性能

- [ ] 在 SiWidget 动画组中添加滚动动画，token为scroll，处理方法与move平行，但在handler中使用scroll而非move
- [ ] 更改 SiScrollArea 的处理逻辑，以使用scroll动画来处理滚动动画

**Comment by ChinaIceF** [comment]
优化了动画行为以减少视觉上的卡顿
